import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function MovieLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="h-screen overflow-x-hidden bg-custom-grey-800 text-custom-light">
        <main className="px-4 py-8">
          <div className="mx-auto max-w-screen-lg">{children}</div>
        </main>
      </body>
    </html>
  );
}

export default MovieLayout;
